apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ovh-dns-updater.fullname" . }}
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ovh-dns-updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ovh-dns-updater.selectorLabels" . | nindent 8 }}
        checksum/configs: {{ include (print $.Template.BasePath "/main.configmap.yaml") . | sha256sum | trunc 63 | trimSuffix "-" }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum | trunc 63 | trimSuffix "-" }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ovh-dns-updater.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: OVH_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ovh-dns-updater.fullname" . }}
                  key: consumerKey
            - name: OVH_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ovh-dns-updater.fullname" . }}
                  key: applicationSecret
            - name: OVH_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ovh-dns-updater.fullname" . }}
                  key: applicationKey
            - name: OVH_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ovh-dns-updater.fullname" . }}
                  key: endpoint
            - name: OVH_DNS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ovh-dns-updater.fullname" . }}
                  key: domain
            - name: OVH_DNS_TTL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ovh-dns-updater.fullname" . }}
                  key: ttl
            - name: SLEEP_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ovh-dns-updater.fullname" . }}
                  key: sleep-time

        - name: {{ .Chart.Name }}-kube-rbac-proxy
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File


          

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
