---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ovh-dns-updater.fullname" . }}
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
data:
  domain: {{ .Values.ovh.domain | quote }}
  endpoint: {{ .Values.ovh.endpoint | quote }}
  ttl: {{ .Values.ovh.ttl | quote }}
  sleep-time: {{ .Values.ovh.sleepTime | quote }}
