apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "ovh-dns-updater.fullname" . }}-leader-election-role
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch