apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "ovh-dns-updater.fullname" . }}-leader-election-role
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "ovh-dns-updater.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ovh-dns-updater.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}