---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ovh-dns-updater.fullname" . }}
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ovh-dns-updater.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ovh-dns-updater.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ovh-dns-updater.fullname" . }}-manager
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ovh-dns-updater.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "ovh-dns-updater.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ovh-dns-updater.fullname" . }}-proxy
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: o{{ template "ovh-dns-updater.fullname" . }}-proxy
subjects:
  - kind: ServiceAccount
    name: {{ include "ovh-dns-updater.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}