apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovh-dns-updater.fullname" . }}
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
type: Opaque
data:
  consumerKey: {{ .Values.ovh.consumerKey | b64enc | quote }}
  applicationKey: {{ .Values.ovh.applicationKey | b64enc | quote }}
  applicationSecret: {{ .Values.ovh.applicationSecret | b64enc | quote }}
